### ISSUE TITLE
Upgrade to use upstream Python3 CMake Logic

### ISSUE THREAD

**Issue by tfoote** [ros2/python_cmake_module#6]
This module uses [PythonInterp](https://cmake.org/cmake/help/latest/module/FindPythonInterp.html) and [PythonLibs](https://cmake.org/cmake/help/latest/module/FindPythonLibs.html) both were deprecated as of Cmake 3.12

The destination we should use is [Python3](https://cmake.org/cmake/help/latest/module/FindPython3.html)

Alternatively the new upstream modules may have enough capabilities to not even need this module itself.

**Comment by sloretz** [comment]
Additional motivation ros2/rosidl_python#137

**Comment by sloretz** [comment]
Assigned self since I have a little time to look at this.

**Comment by sloretz** [comment]
@cottsay I notice [RHEL8 is using CMake 3.11.4](https://www.ros.org/reps/rep-2000.html#galactic-geochelone-may-2021-november-2022). Is it ok to make packages in ROS Rolling require CMake 3.12? Will ROS Humble target a newer version of RHEL with a newer CMake version?

**Comment by cottsay** [comment]
It's actually 3.18: https://github.com/ros-infrastructure/rep/pull/323

**Comment by clalancette** [comment]
@sloretz Did all of the work here get done?  Can we close this?

**Comment by sloretz** [comment]
> @sloretz Did all of the work here get done? Can we close this?

No. A lot of the work got done, but this critical piece did not: https://github.com/ros2/python_cmake_module/pull/7

It's been too long for me to remember what's blocking it.

**Comment by Ryanf55** [comment]
Hey there, FYI, CMake 3.27 is about to be released, which removes these deprecated modules. On distros with rolling releases like MacOS, this could become a problem shortly. 
https://cmake.org/cmake/help/latest/release/3.27.html#deprecated-and-removed-features

**Comment by clalancette** [comment]
I just merged in #7 , which fixes this problem.  So closing.
