### ISSUE TITLE
"Could not find PythonLibs"

### ISSUE THREAD

**Issue by jtbandes** [ros2/python_cmake_module#8]
I'm receiving the following error when trying to use `find_package(launch_testing_ament_cmake)`, which has a transitive dependency on `python_cmake_module`:

```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
  (Required is at least version "3.5")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindPythonLibs.cmake:310 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /opt/ros/galactic/share/python_cmake_module/cmake/Modules/FindPythonExtra.cmake:133 (find_package)
  /opt/ros/galactic/share/launch_testing_ament_cmake/cmake/launch_testing_ament_cmake-extras.cmake:18 (find_package)
  /opt/ros/galactic/share/launch_testing_ament_cmake/cmake/launch_testing_ament_cmakeConfig.cmake:41 (include)
  CMakeLists.txt:31 (find_package)
```

I might be able to hack around this by [setting some CMake variables](https://stackoverflow.com/questions/24174394/cmake-is-not-able-to-find-python-libraries), but I would expect my installed Python version to be found automatically. (Is this related to #6?)

I've installed both `python3` and `python3-dev`:
```
$ python3 --version
Python 3.8.10
```

`uname -a`:
```
Linux ubuntu-linux-20-04-desktop 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:56:23 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

Any help would be appreciated – thanks!

**Comment by sloretz** [comment]
It's possible the work in #6 will fix the issue, but I don't know why `FindPythonLibs` would fail to find python when `python3-dev` is installed.

Does a minimal CMake project have the same issue?

```cmake
cmake_minimum_required(VERSION 3.5)
project(minimal_python_libs_check)

find_package(PythonLibs "3.5" REQUIRED)
```

**Comment by jtbandes** [comment]
I'm not really sure what the root cause was — seemed like changing `project(rosbridge_server NONE)` to `project(rosbridge_server)` helped. Things seem to be working now in https://github.com/RobotWebTools/rosbridge_suite/pull/585. Thanks!

**Comment by sloretz** [comment]
Thanks for reporting that it's working again!

**Comment by felrock** [comment]
I just stumbled upon this issue, running a docker build (cross-compile from x86 to arm64), in the docker image I can verify that i have python3-dev install but cmake will still not find PythonLibs 3.5!

```
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
  (Required is at least version "3.5")
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindPythonLibs.cmake:310 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:3 (find_package)
```
I made a similar minimal CMake project and I have the same issue. But I can see there is a find file _/usr/share/cmake-3.22/Modules/FindPythonLibs.cmake_. python3-dev is installed(3.6) so _/usr/lib/aarch64-linux-gnu/libpython3.6m.so_ exists but for some reason it doesn't match. I also found out that running it twice makes it work...

```
root@879537b01c5d:/opt/ros/foxy/test/build# cmake ..
-- Found PythonLibs: /usr/lib/aarch64-linux-gnu/libpython3.6m.so (found suitable version "3.6.9", minimum required is "3.5") 
```
Might be an CMake issue...

**Comment by felrock** [comment]
I stumbled upon this issue just now, I'm running a docker build(cross-compile to arm64 from x86) and I solved the issue with adding cmake flags to CMake minimal example.

`-DPYTHON_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.6m.so -DPYTHON_INCLUDE_DIR=/usr/lib/include/python3.7`
